import {
	combatLaser,
	grenadeLauncher,
	heavyMachineGun,
	launcher,
	rocketLauncher,
	laserPistol,
	lightningGun,
	swordSaw,
	combatLaser2,
	grenadeLauncher2,
	heavyMachineGun2,
	rocketLauncher2,
	launcher2,
} from './weapons';

export const localfightMachine = [
	{
		id: 'FMUnl-3',
		title: 'UNL-3',
		category: 'Боевая машина',
		image: require('../images/BM/FMUnl-3.jpg'),
		price: 80,
		inBasket: true,
		weapons: [
			combatLaser,
			grenadeLauncher,
			heavyMachineGun,
			rocketLauncher,
			launcher,
		],
		button: '',
	},
	{
		id: 'FMRaptor',
		title: 'Raptor',
		category: 'Боевая машина',
		image: require('../images/BM/FMRaptor.jpg'),
		price: 90,
		inBasket: true,
		weapons: [
			combatLaser,
			grenadeLauncher,
			heavyMachineGun,
			rocketLauncher,
			launcher,
		],
		button: '',
	},
	{
		id: 'FMUNL-2',
		title: 'UNL-2',
		category: 'Боевая машина',
		image: require('../images/BM/FMUNL-2.jpg'),
		price: 100,
		inBasket: true,
		weapons: [
			combatLaser2,
			grenadeLauncher2,
			heavyMachineGun2,
			rocketLauncher2,
			launcher2,
		],
		button: '',
	},
	{
		id: 'FMDinamo',
		title: 'Панцерон Динамо',
		category: 'Боевая машина',
		image: require('../images/BM/FMDinamo.jpg'),
		price: 90,
		inBasket: true,
		weapons: [laserPistol, lightningGun, swordSaw],
		button: '',
	},
	{
		id: 'FMKibero',
		title: 'Панцерон Киберо',
		category: 'Боевая машина',
		image: require('../images/BM/FMKibero.jpg'),
		price: 90,
		inBasket: true,
		weapons: [laserPistol, lightningGun, swordSaw],
		button: '',
	},
	{
		id: 'FMSamuro',
		title: 'Панцерон Самуро',
		category: 'Боевая машина',
		image: require('../images/BM/FMSamuro.jpg'),
		price: 90,
		inBasket: true,
		weapons: [laserPistol, lightningGun, swordSaw],
		button: '',
	},
	{
		id: 'FMCunamo',
		title: 'Панцерон Цунамо',
		category: 'Боевая машина',
		image: require('../images/BM/FMCunamo.jpg'),
		price: 90,
		inBasket: true,
		weapons: [laserPistol, lightningGun, swordSaw],
		button: '',
	},
];
