export const localArmy = [
	//Войска Колдуна
	{
		id: 'VKrotavaryag',
		title: 'Варяг',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Varyagi.jpg'),
		image: require('../images/Koldun/VKrotavaryag.jpg'),
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Улучшено свойство Артефакта. Снижена цена на 10',*/
	},
	{
		id: 'VKGrenaderi',
		title: 'Гренадеры',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Grenaderi.jpg'),
		image: require('../images/Koldun/VKGrenaderi.jpg'),
		price: 160,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Изменено свойство Артефакта',*/
	},
	{
		id: 'VKsupergurony',
		title: 'Гуроны',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Guroni.jpg'),
		image: require('../images/Koldun/VKGurony.jpg'), // Прямой URL для удаленного изображения
		price: 175,
		inBasket: true,

		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 25. Свойства Артефакта уточнены.',*/
	},
	{
		id: 'VKZigfrid',
		title: 'Зигфрид',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Zigfrid.jpg'),
		image: require('../images/Koldun/VKZigfrid.png'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Свойства Артефакта расширены до ОБЕ.',*/
	},
	{
		id: 'VKzigfridmorgenshtern',
		title: 'Зигфрид (старый)',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Zigfrid.jpg'),
		image: require('../images/Koldun/VKzigfridmorgenshtern.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Свойства Артефакта расширены до ОБЕ.',*/
	},
	{
		id: 'VKzigfrid6',
		title: 'Зигфрид (6 бойцов)',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Zigfrid.jpg'),
		image: require('../images/Koldun/VKzigfrid6.png'), // Прямой URL для удаленного изображения
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Свойства Артефакта расширены до ОБЕ.',*/
	},
	{
		id: 'VKkaizer',
		title: 'Кайзер',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Kaizer.jpg'),
		image: require('../images/Koldun/VKKaizer.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 42.13%',
		button: '',
	},
	{
		id: 'VKkondor',
		title: 'Кондор',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Kondor.jpg'),
		image: require('../images/Koldun/VKKondor.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),*/
		/*markerTitle:
			'Снижена цена на 5. Усилено свойство Артефакта, увеличено количество карт до 5',*/
	},
	{
		id: 'VKkondor7',
		title: 'Кондор (7 бойцов)',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Kondor.jpg'),
		image: require('../images/Koldun/VKkondor7.png'), // Прямой URL для удаленного изображения
		price: 265,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Усилено свойство Артефакта.',*/
	},
	{
		id: 'VKmatodor',
		title: 'Матадор',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Matador.jpg'),
		image: require('../images/Koldun/VKMatodor.jpg'), // Прямой URL для удаленного изображения
		price: 175,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5',*/
	},
	{
		id: 'VKneptun',
		title: 'Нептун',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Neptun.jpg'),
		image: require('../images/Koldun/VKneptun.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: 'Вероятность успешного использования артефакта: 75%',
		button: '',
	},
	{
		id: 'VKNorman',
		title: 'Норман',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Norman.jpg'),
		image: require('../images/Koldun/VKNorman.jpg'), // Прямой URL для удаленного изображения
		price: 150,
		inBasket: true,
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Ослаблен Артефакт. Теперь работает только с П',*/
	},
	{
		id: 'VKYatagan',
		title: 'Ятаган',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Yatagan.jpg'),
		image: require('../images/Koldun/VKyatagan.jpg'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Усилен Артефакт.',*/
	},
	{
		id: 'VKAskalon',
		title: 'Аскалон',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Askalon.jpg'),
		image: require('../images/Koldun/VKAskalon.jpg'), // Прямой URL для удаленного изображения
		price: 195,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 55.56%',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Усилен Артефакт.',*/
	},
	{
		id: 'VKAsterisk',
		title: 'Астериск',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Asterisk.jpg'),
		image: require('../images/Koldun/VKAsterisk.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: 'Вероятность выпадения 6: 59.8%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта, увеличена видимость цели.',*/
	},
	{
		id: 'VKgnomi',
		title: 'Боевые Гномы',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Gnomi.jpg'),
		image: require('../images/Koldun/VKgnomi.jpg'), // Прямой URL для удаленного изображения
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Изменено свойство Артефакта.',*/
	},
	{
		id: 'VKVaterloo',
		title: 'Ватерлоо',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Vaterloo.jpg'),
		image: require('../images/Koldun/VKVaterloo.jpg'), // Прямой URL для удаленного изображения
		price: 200,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10.',*/
	},
	{
		id: 'VKvervulf',
		title: 'Вервольф',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Vervulf.jpg'),
		image: require('../images/Koldun/VKvervulf.jpg'), // Прямой URL для удаленного изображения
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 20.',*/
	},
	{
		id: 'VKgidra',
		title: 'Гидра',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Gidra.jpg'),
		image: require('../images/Koldun/VKgidra.jpg'), // Прямой URL для удаленного изображения
		price: 240,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Ослаблен Артефакт. Повышает броню строго до 2',*/
	},
	{
		id: 'VKIzmail',
		title: 'Измаил',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Izmail.jpg'),
		image: require('../images/Koldun/VKIzmail.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Изменено свойство Артефакта.',*/
	},
	{
		id: 'VKKiber-skilet',
		title: 'Кибер-Скелеты',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Kiber-Skileti.png'),
		image: require('../images/Koldun/VKKiber-skilet.jpg'), // Прямой URL для удаленного изображения
		price: 290,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Улучшены характеристики Маневра. Снижена цена на 10. Усилено свойство Артефакта.',*/
	},
	{
		id: 'VKKondung',
		title: 'Конунг',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Kondung.jpg'),
		image: require('../images/Koldun/VKKondung.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Снижена цена на 10. Усилено свойство Артефакта, расширенно до любого противника',*/
	},
	{
		id: 'VKMinotavri',
		title: 'Минотавры',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Minotavri.jpg'),
		image: require('../images/Koldun/VKMinotavri.jpg'), // Прямой URL для удаленного изображения
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'VKChagatai',
		title: 'Чагатай',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Chagatai.jpg'),
		image: require('../images/Koldun/VKChagatai.jpg'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Улучшен Артефакт. Теперь не дает штрафов',*/
	},
	{
		id: 'VKYagelon',
		title: 'Ягеллон',
		category: 'Войска Колдуна',
		description: require('../images/Artefakti/Yagelon.jpg'),
		image: require('../images/Koldun/VKYagelon.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
	},

	//Легионеры Некроманта
	{
		id: 'LNKentavr',
		title: 'Кентавр',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Kentavr.jpg'),
		image: require('../images/Nekromant/LNKentavr.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 20.',*/
	},
	{
		id: 'LNKobra',
		title: 'Кобра',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Kobra.jpg'),
		image: require('../images/Nekromant/LNKobra.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'LNMagnum',
		title: 'Магнум',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Magnum.png'),
		image: require('../images/Nekromant/LNMagnum.png'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 20. Улучшено свойство Артефакта.',*/
	},
	{
		id: 'LNPiton',
		title: 'Питон',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Piton.jpg'),
		image: require('../images/Nekromant/LNPiton.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'LNNekro-Kiborgi_Skeletoni',
		title: 'Скелетоны',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Skeletoni.jpg'),
		image: require('../images/Nekromant/LNNekro-Kiborgi_Skeletoni.jpg'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Изменён текст Артефакта.',*/
	},
	{
		id: 'LNTitan',
		title: 'Титан',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Titan.jpg'),
		image: require('../images/Nekromant/LNTitan.jpg'), // Прямой URL для удаленного изображения
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снинжена цена на 10.',*/
	},
	{
		id: 'LNTornado',
		title: 'Торнадо',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Tornado.jpg'),
		image: require('../images/Nekromant/LNTornado.jpg'), // Прямой URL для удаленного изображения
		price: 235,
		inBasket: true,
		button: '',
		directory: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'LNTornadogolovotyap',
		title: 'Торнадо (7 бойцов)',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Tornado.jpg'),
		image: require('../images/Nekromant/LNTornadogolovotyap.png'), // Прямой URL для удаленного изображения
		price: 275,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'LNUdav',
		title: 'Удав',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Udav.jpg'),
		image: require('../images/Nekromant/LNUdav.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory:
			'Вероятность успешного использования артефакта (воин хотя бы убежит): 67%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),*/
		/*markerTitle:
			'Усилено свойство Артефакта: расстояние выбирается произвольно',*/
	},
	{
		id: 'LNUragan',
		title: 'Ураган',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Uragan.jpg'),
		image: require('../images/Nekromant/LNUragan.jpg'), // Прямой URL для удаленного изображения
		price: 250,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Изменено свойство артефакта',*/
	},
	{
		id: 'LNFobos',
		title: 'Фобос',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Fobos.jpg'),
		image: require('../images/Nekromant/LNFobos.jpg'), // Прямой URL для удаленного изображения
		price: 100,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 55.6%',
		button: '',
	},
	{
		id: 'LNFobos-radist',
		title: 'Фобос (4 бойца)',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Fobos.jpg'),
		image: require('../images/Nekromant/LNFobos-radist.png'), // Прямой URL для удаленного изображения
		price: 130,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 55.6%',
		button: '',
	},
	{
		id: 'LNCunami',
		title: 'Цунами',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Cunami.jpg'),
		image: require('../images/Nekromant/LNCunami.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Снижена цена на 10. Усилено свойство Артефакта: работает сразу после активации',*/
	},
	{
		id: 'LNShipki',
		title: 'Герои Шипки',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Shipki.jpg'),
		image: require('../images/Nekromant/LNShipki.jpg'), // Прямой URL для удаленного изображения
		price: 175,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Изменено свойство артефакта.',*/
	},
	{
		id: 'LNGladius',
		title: 'Гладиус',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Gladius.jpg'),
		image: require('../images/Nekromant/LNGladius.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Изменено свойство Артефакта.',*/
	},
	{
		id: 'LNGornii-Bars',
		title: 'Горный Барс',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Bars.jpg'),
		image: require('../images/Nekromant/LNGornii-Bars.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: 'Вероятность успешного использования артефакта: 83%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта. Повышена вероятность',*/
	},
	{
		id: 'LNGrobag',
		title: 'Гробаг',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Grobak.jpg'),
		image: require('../images/Nekromant/LNGrobag.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 30.56%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10.',*/
	},
	{
		id: 'LNGulrog',
		title: 'Гулрог',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/gulrog.jpg'),
		image: require('../images/Nekromant/LNGulrog.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'LNGugluk',
		title: 'Гуглук',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Gugluk.jpg'),
		image: require('../images/Nekromant/LNGugluk.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5',*/
	},
	{
		id: 'LNYedinorog',
		title: 'Единорог',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Edinorog.jpg'),
		image: require('../images/Nekromant/LNYedinorog.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5',*/
	},
	{
		id: 'LNKechya',
		title: 'Кечуа',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Kechua.jpg'),
		image: require('../images/Nekromant/LNKechya.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'LNNekros',
		title: 'Некрос',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Nekros.jpg'),
		image: require('../images/Nekromant/LNNekros.jpg'), // Прямой URL для удаленного изображения
		price: 260,
		inBasket: true,
		directory:
			'Вероятность успешного использования Артефакта в 5 воинов: 59.8%; в 4 воина: 51.8%; в 3 воина: 42.1%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10',*/
	},
	{
		id: 'LNStrazhi-grobnits',
		title: 'Стражи Гробниц',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Strazi-grobnic.jpg'),
		image: require('../images/Nekromant/LNStrazhi-grobnits.jpg'), // Прямой URL для удаленного изображения
		price: 220,
		inBasket: true,
		directory:
			'Вероятность смерти воина при успешном использовании артефакта: 33.33%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта.',*/
	},
	{
		id: 'LNStrazhi-Tmi',
		title: 'Стражи Тьмы',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Straci-tmi.jpg'),
		image: require('../images/Nekromant/LNStrazhi-Tmi.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: 'Вероятность успешного использования артефакта: 33.33%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Снижена цена на 15. Изменены характеристики. Усилен Артефакт, повышена вероятность',*/
	},
	{
		id: 'LNUruk-Tag',
		title: 'Урук-Таг',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Urug-tag.jpg'),
		image: require('../images/Nekromant/LNUruk-Tag.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 67%',
		button: '',
	},
	{
		id: 'LNHatamoto',
		title: 'Хатамото',
		category: 'Легионеры Некроманта',
		description: require('../images/Artefakti/Hatamoto.jpg'),
		image: require('../images/Nekromant/LNHatamoto.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
	},

	//Гвардия Чародея
	{
		id: 'GCHAmazonki',
		title: 'Амазонки',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Amazonki.jpg'),
		image: require('../images/Charodei/GCHAmazonki.jpg'), // Прямой URL для удаленного изображения
		price: 175,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'GCHBagration',
		title: 'Багратион',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Bagration.jpg'),
		image: require('../images/Charodei/GCHBagration.jpg'),
		price: 175,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Артефакт переформулирован',*/
	},
	{
		id: 'GCHVarani',
		title: 'Вараны',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Varani.jpg'),
		image: require('../images/Charodei/GCHVarani.jpg'),
		price: 260,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 55.56%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилена вероятность успешного использования Артефакта',*/
	},
	{
		id: 'GCHMarsel',
		title: 'Марсель',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Marsel.jpg'),
		image: require('../images/Charodei/GCHMarsel.jpg'),
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта: работает на любом противнике.',*/
	},
	{
		id: 'GCHPoseidon',
		title: 'Посейдон',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Poseidon.jpg'),
		image: require('../images/Charodei/GCHPoseidon.jpg'),
		price: 160,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 33,33%',
		button: '',
	},
	{
		id: 'GCHSokol',
		title: 'Сокол',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Sokol.jpg'),
		image: require('../images/Charodei/GCHSokol.jpg'),
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшена стоимость на 20. Ослаблено свойство Артефакта',*/
	},
	{
		id: 'GCHStalingrad',
		title: 'Сталинград',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Stalingrad.jpg'),
		image: require('../images/Charodei/GCHStalingrad.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 55.6%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Изменены допуски к орудиям.',*/
	},
	{
		id: 'GCHTaifun',
		title: 'Тайфун',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Taifun.jpg'),
		image: require('../images/Charodei/GCHTaifun.jpg'), // Прямой URL для удаленного изображения
		price: 260,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'GCHCenturion',
		title: 'Центурион',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Centurion.jpg'),
		image: require('../images/Charodei/GCHCenturion.jpg'), // Прямой URL для удаленного изображения
		price: 165,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 16,6%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшена цена на 5. Усилено свойство Артефакта',*/
	},
	{
		id: 'GCHEspada',
		title: 'Эспада',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Espada.jpg'),
		image: require('../images/Charodei/GCHEspada.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 83,4%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшена цена на 10.',*/
	},
	{
		id: 'GCHAvalon',
		title: 'Авалон',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Avalon.png'),
		image: require('../images/Charodei/GCHAvalon.png'), // Прямой URL для удаленного изображения
		price: 195,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Увеличена цена на 5.',*/
	},
	{
		id: 'GCHBorodino',
		title: 'Бородино',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Borodino.png'),
		image: require('../images/Charodei/GCHBorodino.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшена цена на 5. Изменена формулировка Артефакта',*/
	},
	{
		id: 'GCHVolkodav',
		title: 'Волкодав',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Volkodav.png'),
		image: require('../images/Charodei/GCHVolkodav.png'), // Прямой URL для удаленного изображения
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'GCHKanopus',
		title: 'Канопус',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Kanopus.png'),
		image: require('../images/Charodei/GCHKanopus.png'), // Прямой URL для удаленного изображения
		price: 280,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшены допуски к орудиям у командира',*/
	},
	{
		id: 'GCHVolnica',
		title: 'Кубанская Вольница',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Volnica.png'),
		image: require('../images/Charodei/GCHVolnica.png'), // Прямой URL для удаленного изображения
		price: 195,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта 33,33%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Уменьшена цена на 5.',*/
	},
	{
		id: 'GCHPaladini',
		title: 'Паладины',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Paladini.png'),
		image: require('../images/Charodei/GCHPaladini.png'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 33.33%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Увеличена вероятность успешного использования Артефакта.',*/
	},
	{
		id: 'GCHPoltava',
		title: 'Полтава',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Poltava.png'),
		image: require('../images/Charodei/GCHPoltava.png'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Снижена цена на 5. Усилено свойство Артефакта: повышен радиус с 8 до 10 шагов.',*/
	},
	{
		id: 'GCHSkifi',
		title: 'Скифы',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Skifi.png'),
		image: require('../images/Charodei/GCHSkifi.png'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10',*/
	},
	{
		id: 'GCHElitar',
		title: 'Элитар',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Elitar.png'),
		image: require('../images/Charodei/GCHElitar.png'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Изменено свойство Артефакта',*/
	},
	{
		id: 'GCHYastreb',
		title: 'Ястреб',
		category: 'Гвардия Чародея',
		description: require('../images/Artefakti/Yastreb.png'),
		image: require('../images/Charodei/GCHYastreb.png'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 67%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 10. Улучшены характеристики Маневра',*/
	},
	//Гильдия Вольных Стрелков
	{
		id: 'GVSberkut',
		title: 'Беркут',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Berkut.jpg'),
		image: require('../images/GVS/GVSberkut.jpg'), // Относительный путь для локального изображения
		price: 200,
		inBasket: true,
		directory: 'Вероятность выпадения 5,6: 33.33%',
		button: 'green',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта',*/
	},
	{
		id: 'GVSvepr',
		title: 'Вепрь',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Vepr.jpg'),
		image: require('../images/GVS/GVSvepr.jpg'), // Прямой URL для удаленного изображения
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта. Изменен принцип возрождения',*/
	},
	{
		id: 'GVSversal',
		title: 'Версаль',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Versal.jpg'),
		image: require('../images/GVS/GVSversal.jpg'), // Прямой URL для удаленного изображения
		price: 165,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 15. Измменены допуски к орудиям',*/
	},
	{
		id: 'GVSpsivoini',
		title: 'Псы Войны',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Psi-Voini.jpg'),
		image: require('../images/GVS/GVSpsivoini.jpg'), // Прямой URL для удаленного изображения
		price: 200,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
	},
	{
		id: 'GVSpushkari',
		title: 'Пушкари',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Pushkari.jpg'),
		image: require('../images/GVS/GVSpushkari.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Артефакт уточнен',*/
	},
	{
		id: 'GVSrodezia',
		title: 'Родезия',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Rodeziya.jpg'),
		image: require('../images/GVS/GVSrodezia.jpg'), // Прямой URL для удаленного изображения
		price: 215,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Артефакт уточнен',*/
	},
	{
		id: 'GVSsaturn',
		title: 'Сатурн',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Saturn.jpg'),
		image: require('../images/GVS/GVSsaturn.jpg'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Артефакт ослаблен',*/
	},
	{
		id: 'GVSshervud',
		title: 'Шервуд',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Shervud.jpg'),
		image: require('../images/GVS/GVSshervud.jpg'), // Прямой URL для удаленного изображения
		price: 165,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'GVSbiokiborgysherify',
		title: 'Шерифы',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Sherifi.jpg'),
		image: require('../images/GVS/GVSbiokiborgysherify.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: 'xt gbcfnm z [p',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Изменены допуски к орудиям',*/
	},
	{
		id: 'GVSvoinymirty',
		title: 'Воины Митры',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Mitri.png'),
		image: require('../images/GVS/GVSvoinymirty.png'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 30.56%',
		button: 'xt gbcfnm z [p',
	},
	{
		id: 'GVSgladiatory',
		title: 'Гладиатор',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Gladiator.png'),
		image: require('../images/GVS/GVSgladiatory.png'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'GVSpsi-komandazero',
		title: 'Пси-команда Зеро',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Zero.png'),
		image: require('../images/GVS/GVSpsi-komandazero.png'), // Прямой URL для удаленного изображения
		price: 200,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 67%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Изменены допуски к орудиям.',*/
	},
	{
		id: 'GVSkentavry',
		title: 'Кентавры',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Kentavri.png'),
		image: require('../images/GVS/GVSkentavry.png'), // Прямой URL для удаленного изображения
		price: 260,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 10',*/
	},
	{
		id: 'GVSmorskoye-bratstvo',
		title: 'Морское братство',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Morskoe-bratstvo.png'),
		image: require('../images/GVS/GVSmorskoye-bratstvo.png'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10',*/
	},
	{
		id: 'GVSnovaya-sibir',
		title: 'Новая сибирь',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/sibir.png'),
		image: require('../images/GVS/GVSnovaya-sibir.png'), // Прямой URL для удаленного изображения
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижены характеристики Маневра',*/
	},
	{
		id: 'GVSroksburg',
		title: 'Роксбург',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Roksburg.png'),
		image: require('../images/GVS/GVSroksburg.png'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Изменено свойство Артефакта',*/
	},
	{
		id: 'GVStarasov-kuren',
		title: 'Тарасов курень',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Kuren.png'),
		image: require('../images/GVS/GVStarasov-kuren.png'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Усилено свойство Артефакта',*/
	},
	{
		id: 'GVStemnya-sotnya',
		title: 'Тёмная сотня',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Temnaya-Sotnya.png'),
		image: require('../images/GVS/GVStemnya-sotnya.png'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10.',*/
	},
	{
		id: 'GVSyupiter',
		title: 'Юпитер',
		category: 'Гильдия вольных стрелков',
		description: require('../images/Artefakti/Ypiter.png'),
		image: require('../images/GVS/GVSyupiter.png'), // Прямой URL для удаленного изображения
		price: 165,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},

	//Сторонние производиттели

	{
		id: 'SPDrakonoborci',
		title: 'Драконоборцы',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Drakonoborci.jpg'),
		image: require('../images/Storonie/SPDrakonoborci.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKamlak',
		title: 'Камлак',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Kamlak.jpg'),
		image: require('../images/Storonie/SPKamlak.jpg'), // Прямой URL для удаленного изображения
		price: 240,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10. Изменены допуски к орудиям',*/
	},
	{
		id: 'SPKitoboi',
		title: 'Китобои',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Kitoboi.jpg'),
		image: require('../images/Storonie/SPKitoboi.jpg'), // Прямой URL для удаленного изображения
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5',*/
	},
	{
		id: 'SPKricheri',
		title: 'Кричеры',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Kricheri.jpg'),
		image: require('../images/Storonie/SPKricheri.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышеня цена на 20',*/
	},

	{
		id: 'SPPredvestniki4',
		title: 'Предвестники',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Predvestniki.jpg'),
		image: require('../images/Storonie/SPPredvestniki4.jpg'), // Прямой URL для удаленного изображения
		price: 155,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышеня цена на 5',*/
	},
	{
		id: 'SPPredvestniki5',
		title: 'Предвестники (5 бойцов)',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Predvestniki.jpg'),
		image: require('../images/Storonie/SPPredvestniki5.jpg'), // Прямой URL для удаленного изображения
		price: 195,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышеня цена на 5',*/
	},
	{
		id: 'SPStragiGizi',
		title: 'Стражи Гизы',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/StragiGizi.jpg'),
		image: require('../images/Storonie/SPStragiGizi.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 10',*/
	},
	{
		id: 'SPTechKnight',
		title: 'Технорыцари',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/TechKnight.jpg'),
		image: require('../images/Storonie/SPTechKnight.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилен Артефакт.',
	},
	{
		id: 'SPHardkor',
		title: 'отряд Хардкор',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Hardkor.jpg'),
		image: require('../images/Storonie/SPHardkor.jpg'),
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPOmicsir',
		title: 'Омиксир',
		category: 'База (КБФ)',
		description: require('../images/Artefakti/Omicsir.jpg'),
		image: require('../images/Storonie/SPOmicsir.jpg'),
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPShotrm',
		title: 'Био-взвод Шторм',
		category: 'База (КБФ)',
		description: require('../images/Artefakti/Shotrm.jpg'),
		image: require('../images/Storonie/SPShotrm.jpg'),
		price: 220,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKallisto',
		title: 'Каллисто',
		category: 'Нейтральный отряд (КБФ)',
		description:
			'https://sun9-12.userapi.com/impg/bvR7cJyi5lLMPiwmNuAH-Ap47j87SOJ9st3y2Q/e48La_SU8U8.jpg?size=1090x726&quality=95&sign=a4cf18e61919cd11f379c0416d373c49&type=album',
		image: require('../images/Storonie/SPKallisto.jpg'),
		price: 260,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPDemoniSulfura',
		title: 'Демоны Сульфура',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/DemoniSulfura.jpg'),
		image: require('../images/Storonie/SPDemoniSulfura.jpg'),
		price: 130,
		inBasket: true,
		directory:
			'Вероятность успешного использования Артефакта при 0 сброшенных карт: 33,33%; при 1 сброшенной карте: 55.6%; при 2 сброшенных картах: 70.37%',
		button: '',
	},
	{
		id: 'SPLizardi',
		title: 'Лизарды',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Lizardi.jpg'),
		image: require('../images/Storonie/SPLizardi.jpg'),
		price: 150,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 67% ',
		button: '',
	},
	{
		id: 'SPKlanLokAmon',
		title: 'Лок`Амон',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/LokAmon.jpg'),
		image: require('../images/Storonie/SPKlanLokAmon.jpg'),
		price: 165,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKlanLokAmon5',
		title: 'Лок`Амон (5 бойцов)',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/LokAmon.jpg'),
		image: require('../images/Storonie/SPKlanLokAmon5.jpg'),
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPOrkestrSmerty',
		title: 'Оркестр Смерти',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/OrkestrSmerty.jpg'),
		image: require('../images/Storonie/SPOrkestrSmerty.jpg'),
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPGendarmes',
		title: 'Жандармы',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/Gendarmes.jpg'),
		image: require('../images/Storonie/SPGendarmes.jpg'),
		price: 200,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPYarostNebes',
		title: 'Ярость Небес',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/YarostNebes.jpg'),
		image: require('../images/Storonie/SPYarostNebes.jpg'),
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPNeukronimie',
		title: 'Неукротимые',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Neukronimie.jpg'),
		image: require('../images/Storonie/SPNeukronimie.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPVedmaki',
		title: 'Отряд Ведьмаки',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Vedmaki.jpg'),
		image: require('../images/Storonie/SPVedmaki.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPVerniePrinc',
		title: 'Верные Принцу',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/VerniePrinc.jpg'),
		image: require('../images/Storonie/SPVerniePrinc.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'SPGeroyBilin',
		title: 'Герои былин',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/GeroyBilin.jpg'),
		image: require('../images/Storonie/SPGeroyBilin.jpg'), // Прямой URL для удаленного изображения
		price: 210,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 33.33%',
		button: '',
	},
	{
		id: 'SPHichniki',
		title: 'Отряд Хищники',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Hichniki.jpg'),
		image: require('../images/Storonie/SPHichniki.jpg'), // Прямой URL для удаленного изображения
		price: 330,
		inBasket: true,
		directory:
			'Вероятность успешного использования Артефакта в 5 воинов: 91.2%; в 4 воина: 80.25%; в 3 воина:  70.37%; в 2 воина: 55.56%.',
		button: '',
	},
	{
		id: 'SPChempioniAreni',
		title: 'Чемпионы Арены',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/ChempioniAreni.jpg'),
		image: require('../images/Storonie/SPChempioniAreni.jpg'), // Прямой URL для удаленного изображения
		price: 255,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5. Ослаблено свойство Артефакта.',*/
	},
	{
		id: 'SPGally',
		title: 'Галлы',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Gally.jpg'),
		image: require('../images/Storonie/SPGally.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
	},
	{
		id: 'SPChasticiRazuma',
		title: 'Частицы Разума',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/ChasticiRazuma.jpg'),
		image: require('../images/Storonie/SPChasticiRazuma.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKiberici',
		title: 'Киберийцы',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Kiberici.jpg'),
		image: require('../images/Storonie/SPKiberici.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKsenohanteri',
		title: 'Ксенохантеры',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Ksenohanteri.jpg'),
		image: require('../images/Storonie/SPKsenohanteri.jpg'), // Прямой URL для удаленного изображения
		price: 195,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'SPStalnayaPyaterka',
		title: 'Стальная Пятерка',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/StalnayaPyaterka.jpg'),
		image: require('../images/Storonie/SPStalnayaPyaterka.jpg'), // Прямой URL для удаленного изображения
		price: 255,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPValhalla',
		title: 'Вальхалла',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Valhalla.jpg'),
		image: require('../images/Storonie/SPValhalla.jpg'), // Прямой URL для удаленного изображения
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPShampanoidi',
		title: 'Шампаноиды',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Shampanoidi.jpg'),
		image: require('../images/Storonie/SPShampanoidi.jpg'), // Прямой URL для удаленного изображения
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPTangar',
		title: 'Тангар',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Tangar.jpg'),
		image: require('../images/Storonie/SPTangar.jpg'), // Прямой URL для удаленного изображения
		price: 270,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPTropik',
		title: 'Тропик',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Tropik.jpg'),
		image: require('../images/Storonie/SPTropik.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPHorni',
		title: 'Хорны',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Horni.jpg'),
		image: require('../images/Storonie/SPHorni.jpg'), // Прямой URL для удаленного изображения
		price: 230,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPBladhorn',
		title: 'Бладхорн',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Bladhorn.jpg'),
		image: require('../images/Storonie/SPBladhorn.jpg'), // Прямой URL для удаленного изображения
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPBorciZaOgon',
		title: 'Борцы за Огонь',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/BorciZaOgon.jpg'),
		image: require('../images/Storonie/SPBorciZaOgon.jpg'), // Прямой URL для удаленного изображения
		price: 165,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'SPBratyaIgarashi',
		title: 'Братья Игараши',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/BratyaIgarashi.jpg'),
		image: require('../images/Storonie/SPBratyaIgarashi.jpg'), // Прямой URL для удаленного изображения
		price: 200,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPValkirii',
		title: 'Валькирии',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Valkirii.jpg'),
		image: require('../images/Storonie/SPValkirii.jpg'), // Прямой URL для удаленного изображения
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPGoblinilesa',
		title: 'Гоблины дикого леса',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Goblinilesa.jpg'),
		image: require('../images/Storonie/SPGoblinilesa.jpg'), // Прямой URL для удаленного изображения
		price: 160,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPDagaz',
		title: 'Дагаз',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Dagaz.jpg'),
		image: require('../images/Storonie/SPDagaz.jpg'),
		price: 180,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPDerzkayaStaya',
		title: 'Дерзкая Стая',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/DerzkayaStaya.jpg'),
		image: require('../images/Storonie/SPDerzkayaStaya.jpg'), // Прямой URL для удаленного изображения
		price: 235,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPMinoni',
		title: 'Банда Миньоны',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Minoni.jpg'),
		image: require('../images/Storonie/SPMinoni.jpg'),
		price: 150,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPFangeti',
		title: 'Фангеты',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/Fangeti.jpg'),
		image: require('../images/Storonie/SPFangeti.jpg'), // Прямой URL для удаленного изображения
		price: 190,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPCherniRassvet',
		title: 'Чёрный Рассвет',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/CherniRassvet.jpg'),
		image: require('../images/Storonie/SPCherniRassvet.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Понижена цена на 5.',*/
	},
	{
		id: 'SPPodrugiAiri',
		title: 'Подруги Айры',
		category: 'Альянс Свободных (КБФ)',
		description: require('../images/Artefakti/PodrugiAiri.jpg'),
		image: require('../images/Storonie/SPPodrugiAiri.jpg'), // Прямой URL для удаленного изображения
		price: 250,
		inBasket: true,
		directory: '',
		button: '',
	},

	{
		id: 'SPNewAmazonki',
		title: 'Новые Амазонки',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/NewAmazonki.jpg'),
		image: require('../images/Storonie/SPNewAmazonki.jpg'), // Прямой URL для удаленного изображения
		price: 240,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'oskal_Nochi',
		title: 'Оскал Ночи',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/oskal_Nochi.jpg'),
		image: require('../images/Storonie/oskal_Nochi.jpg'), // Прямой URL для удаленного изображения
		price: 205,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Повышена цена на 5. Изменено свойство Артефакта: госпиталь заменен на ранение',*/
	},
	{
		id: 'SPPesherniLudi',
		title: 'Пещерные Люди',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/PesherniLudi.jpg'),
		image: require('../images/Storonie/SPPesherniLudi.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'SPFemiskira',
		title: 'Фемискира',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/Femiskira.jpg'),
		image: require('../images/Storonie/SPFemiskira.jpg'), // Прямой URL для удаленного изображения
		price: 170,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPCherni_Ricari',
		title: 'Чёрные рыцари',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/Cherni_Ricari.jpg'),
		image: require('../images/Storonie/SPCherni_Ricari.jpg'), // Прямой URL для удаленного изображения
		price: 140,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPShinobi',
		title: 'Клан Шиноби',
		category: 'Войско павшего мага (КБФ)',
		description: require('../images/Artefakti/Shinobi.jpg'),
		image: require('../images/Storonie/SPShinobi.jpg'), // Прямой URL для удаленного изображения
		price: 185,
		inBasket: true,
		directory:
			'Вероятность успешного использования артефакта при броске 2-х кубиков: 75%',
		button: '',
	},
	{
		id: 'SPBergi',
		title: 'Берги',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/SPBergi.jpg'),
		image: require('../images/Storonie/SPBergi.jpg'), // Прямой URL для удаленного изображения
		price: 300,
		inBasket: true,
		directory:
			'Вероятность успешного использования Артефакта при броске 3 кубиков: 16,6%; ',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 10.',*/
	},
	{
		id: 'SPHraniteliRochi',
		title: 'Хранители Рощи',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/HraniteliRochi.jpg'),
		image: require('../images/Storonie/SPHraniteliRochi.jpg'), // Прямой URL для удаленного изображения
		price: 240,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPGornyaki',
		title: 'Горняки',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Gornyaki.jpg'),
		image: require('../images/Storonie/SPGornyaki.jpg'), // Прямой URL для удаленного изображения
		price: 260,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPGromoboi',
		title: 'Громобои',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Gromoboi.jpg'),
		image: require('../images/Storonie/SPGromoboi.jpg'), // Прямой URL для удаленного изображения
		price: 275,
		inBasket: true,
		directory: '',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPKiberzveri',
		title: 'Киберзвери',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Kiberzveri.jpg'),
		image: require('../images/Storonie/SPKiberzveri.jpg'), // Прямой URL для удаленного изображения
		price: 290,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPSumerechniStrazhi',
		title: 'Сумеречные стражи',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/SumerechniStrazhi.jpg'),
		image: require('../images/Storonie/SPSumerechniStrazhi.jpg'), // Прямой URL для удаленного изображения
		price: 245,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle:
			'Снижена цена на 5. Изменено свойство Артефакта: воин исцеляется в стартовую зону',*/
	},
	{
		id: 'SPTvoreniyaMarkusa',
		title: 'Творения Маркуса',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/TvoreniyaMarkusa.jpg'),
		image: require('../images/Storonie/SPTvoreniyaMarkusa.jpg'), // Прямой URL для удаленного изображения
		price: 260,
		inBasket: true,
		directory: '',
		button: '',
		marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Усилено свойство Артефакта',
	},
	{
		id: 'SPZhneci',
		title: 'Темные Жнецы',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Zhneci.jpg'),
		image: require('../images/Storonie/SPZhneci.jpg'), // Прямой URL для удаленного изображения
		price: 225,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 42.13%',
		button: '',
		/*marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Снижена цена на 5.',*/
	},
	{
		id: 'SPTritalianci',
		title: 'Триталианцы',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Tritalianci.jpg'),
		image: require('../images/Storonie/SPTritalianci.jpg'), // Прямой URL для удаленного изображения
		price: 255,
		inBasket: true,
		directory: '',
		button: '',
		/*	marker: require('../images/Exclamation_marker.png'),
		markerTitle: 'Повышена цена на 5.',*/
	},
	{
		id: 'SPChama-Tor',
		title: 'Чама-Тор',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Chama-Tor.jpg'),
		image: require('../images/Storonie/SPChama-Tor.jpg'), // Прямой URL для удаленного изображения
		price: 300,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKhakylmoa',
		title: 'Воины К`хакульмоа',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Khakylmoa.jpg'),
		image: require('../images/Storonie/SPKhakylmoa.jpg'), // Прямой URL для удаленного изображения
		price: 200,
		inBasket: true,
		directory: '',
		button: '',
	},
	{
		id: 'SPKromeshniki',
		title: 'Кромешники',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Kromeshniki.jpg'),
		image: require('../images/Storonie/SPKromeshniki.jpg'),
		price: 290,
		inBasket: true,
		directory: 'Вероятность успешного использования Артефакта: 67%',
		button: '',
	},
	{
		id: 'SPDikobrazi',
		title: 'Дикобразы',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Dikobrazi.jpg'),
		image: require('../images/Storonie/SPDikobrazi.jpg'),
		price: 230,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPObitateliBelihRavnin',
		title: 'Об-ли Белых Равнин',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/ObitateliBelihRavnin.jpg'),
		image: require('../images/Storonie/SPObitateliBelihRavnin.jpg'),
		price: 195,
		inBasket: false,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPmrachnaya_Krasotka',
		title: 'Мрачная Красотка',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/mrachnaya_Krasotka.jpg'),
		image: require('../images/Storonie/SPmrachnaya_Krasotka.jpg'),
		price: 275,
		inBasket: false,
		directory: 'Вероятность успешного использования Артефакта: 67%',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPPozhirateli_Mirov',
		title: 'Пожиратели Миров',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Pozhirateli_Mirov.jpg'),
		image: require('../images/Storonie/SPPozhirateli_Mirov.jpg'),
		price: 310,
		inBasket: false,
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPTriton',
		title: 'Тритон',
		category: 'База (КБФ)',
		description: require('../images/Artefakti/Triton.jpg'),
		image: require('../images/Storonie/SPTriton.jpg'),
		price: 200,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPGornila',
		title: 'Песнь Горнила',
		category: 'База (КБФ)',
		description: require('../images/Artefakti/Gornila.jpg'),
		image: require('../images/Storonie/SPGornila.jpg'),
		price: 240,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPDzyanshi',
		title: 'Дзяньши',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Dzyanshi.jpg'),
		image: require('../images/Storonie/SPDzyanshi.jpg'),
		price: 170,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPKrasnaya_Zvezda',
		title: 'Красная Звезда',
		category: 'Х-Бункер (КБФ)',
		description: require('../images/Artefakti/Krasnaya_Zvezda.jpg'),
		image: require('../images/Storonie/SPKrasnaya_Zvezda.jpg'),
		price: 160,
		inBasket: false,
		directory: 'Вероятность успешного использования Артефакта: 33.33%',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPDraugry',
		title: 'Драугры',
		category: 'Нейтральный отряд (КБФ)',
		description: require('../images/Artefakti/SPDraugry.jpg'),
		image: require('../images/Storonie/SPDraugry.jpg'),
		price: 195,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPTemnyy_Lik',
		title: 'Тёмный Лик',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Temnyy_Lik.jpg'),
		image: require('../images/Storonie/SPTemnyy_Lik.jpg'),
		price: 290,
		inBasket: false,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPKrovavoe_Kopito',
		title: 'Кровавое Копыто',
		category: 'Воители иных миров (КБФ)',
		description: require('../images/Artefakti/Krovavoe_Kopito.jpg'),
		image: require('../images/Storonie/SPKrovavoe_Kopito.jpg'),
		price: 255,
		inBasket: false,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPSlughitely_Aznaira',
		title: 'Служители Азнаира',
		category: 'Легионы черной планеты (КБФ)',
		description: require('../images/Artefakti/Slughitely_Aznaira.jpg'),
		image: require('../images/Storonie/SPSlughitely_Aznaira.jpg'),
		price: 210,
		inBasket: false,
		directory: '',
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},

	//Отряды АОБФ
	{
		id: 'SPRenegaty_Haosa',
		title: 'Ренегаты Хаоса',
		category: 'База (АОБФ)',
		description: require('../images/Artefakti/Renegaty_Haosa.jpg'),
		image: require('../images/Storonie/SPRenegaty_Haosa.jpg'),
		price: 180,
		inBasket: false,
		directory: 'Вероятность успешного использования Артефакта: 33.33%',
		button: '',
	},
	{
		id: 'SPStrazhy_Ra',
		title: 'Стражи Ра',
		category: 'База (АОБФ)',
		description: require('../images/Artefakti/Strazhy_Ra.jpg'),
		image: require('../images/Storonie/SPStrazhy_Ra.jpg'),
		price: 220,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPKamennie_Trolly',
		title: 'Каменные Тролли',
		category: 'Войско павшего мага (АОБФ)',
		description: require('../images/Artefakti/Kamennie_Trolly.jpg'),
		image: require('../images/Storonie/SPKamennie_Trolly.jpg'),
		price: 250,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPProidohi',
		title: 'Пройдохи',
		category: 'Войско павшего мага (АОБФ)',
		description: require('../images/Artefakti/Proidohi.jpg'),
		image: require('../images/Storonie/SPProidohi.jpg'),
		price: 145,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPRusskie_Skazky',
		title: 'Русские Сказки',
		category: 'Войско павшего мага (АОБФ)',
		description: require('../images/Artefakti/Russkie_Skazky.jpg'),
		image: require('../images/Storonie/SPRusskie_Skazky.jpg'),
		price: 230,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPHitrobany',
		title: 'Хитрованы',
		category: 'Войско павшего мага (АОБФ)',
		description: require('../images/Artefakti/Hitrobany.jpg'),
		image: require('../images/Storonie/SPHitrobany.jpg'),
		price: 145,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPCrazy_food',
		title: 'Crazy Food',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Crazy_food.jpg'),
		image: require('../images/Storonie/SPCrazy_food.jpg'),
		price: 170,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPApus',
		title: 'Апус',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Apus.jpg'),
		image: require('../images/Storonie/SPApus.jpg'),
		price: 200,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPBezlikie',
		title: 'Безликие',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Bezlikie.jpg'),
		image: require('../images/Storonie/SPBezlikie.jpg'),
		price: 190,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPBremensky_Muzic',
		title: 'Бременские Музыканты',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Bremensky_Muzic.jpg'),
		image: require('../images/Storonie/SPBremensky_Muzic.jpg'),
		price: 185,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPGromovie_Kulaki',
		title: 'Громовые Кулаки',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Gromovie_Kulaki.jpg'),
		image: require('../images/Storonie/SPGromovie_Kulaki.jpg'),
		price: 290,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPKarabashsky_Trolli',
		title: 'Карабашские Тролли',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Karabashsky_Trolli.jpg'),
		image: require('../images/Storonie/SPKarabashsky_Trolli.jpg'),
		price: 205,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPKimy',
		title: 'Кими',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Kimy.jpg'),
		image: require('../images/Storonie/SPKimy.jpg'),
		price: 220,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPMonstryDVD',
		title: 'Монстры DVD-проката',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/MonstryDVD.jpg'),
		image: require('../images/Storonie/SPMonstryDVD.jpg'),
		price: 180,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPStepnie_Velikany',
		title: 'Степные Великаны',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Stepnie_Velikany.jpg'),
		image: require('../images/Storonie/SPStepnie_Velikany.jpg'),
		price: 120,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPUzniky_Culfura',
		title: 'Узники Сульфура',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Uzniky_Culfura.jpg'),
		image: require('../images/Storonie/SPUzniky_Culfura.jpg'),
		price: 140,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPVisoky_Kolpaky',
		title: 'Высокие Колпаки',
		category: 'Нейтралы (АОБФ)',
		description: require('../images/Artefakti/Visoky_Kolpaky.jpg'),
		image: require('../images/Storonie/SPVisoky_Kolpaky.jpg'),
		price: 135,
		inBasket: false,
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPBrigada',
		title: 'Бригада',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Brigada.jpg'),
		image: require('../images/Storonie/SPBrigada.jpg'),
		price: 160,
		inBasket: false,
		directory:
			'Вероятность успешного использования Артефакта при броске 4 кубиков: 51.8%, 3 кубиков: 42.1%',
		button: '',
	},
	{
		id: 'SPZeleznaya_Orda',
		title: 'Вожди Железной Орды',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Zeleznaya_Orda.jpg'),
		image: require('../images/Storonie/SPZeleznaya_Orda.jpg'),
		price: 220,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPGornie_Klani',
		title: 'Горные Кланы',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Gornie_Klani.jpg'),
		image: require('../images/Storonie/SPGornie_Klani.jpg'),
		price: 290,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPDolg',
		title: 'Долг',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Dolg.jpg'),
		image: require('../images/Storonie/SPDolg.jpg'),
		price: 225,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPZhelezni_Drakon',
		title: 'Клан Железного Дракона',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Zhelezni_Drakon.jpg'),
		image: require('../images/Storonie/SPZhelezni_Drakon.jpg'),
		price: 185,
		inBasket: false,
		directory: '',
		button: '',
	},
	{
		id: 'SPLesnie_Vedmi',
		title: 'Лесные Ведьмы',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Lesnie_Vedmi.jpg'),
		image: require('../images/Storonie/SPLesnie_Vedmi.jpg'),
		price: 190,
		inBasket: false,
		directory: 'Вероятность успешного использования артефакта: 30.5%',
		button: '',
	},
	{
		id: 'SPMeotida',
		title: 'Меотида',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Meotida.jpg'),
		image: require('../images/Storonie/SPMeotida.jpg'),
		price: 170,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPMertvi_Kosmos',
		title: 'Мертвый Космос',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Mertvi_Kosmos.jpg'),
		image: require('../images/Storonie/SPMertvi_Kosmos.jpg'),
		price: 170,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPNechistaya_Sila',
		title: 'Нечистая Сила',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Nechistaya_Sila.jpg'),
		image: require('../images/Storonie/SPNechistaya_Sila.jpg'),
		price: 195,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPOtdel_Z',
		title: 'Отдел Зет',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Otdel_Z.jpg'),
		image: require('../images/Storonie/SPOtdel_Z.jpg'),
		price: 155,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPOhotniki_na_Mamontov',
		title: 'Охотники На Мамонтов',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Ohotniki_na_Mamontov.jpg'),
		image: require('../images/Storonie/SPOhotniki_na_Mamontov.jpg'),
		price: 155,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPOhotnici_za_Golovami',
		title: 'Охотницы За Головами',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Ohotnici_za_Golovami.jpg'),
		image: require('../images/Storonie/SPOhotnici_za_Golovami.jpg'),
		price: 170,
		inBasket: false,
		directory: 'Вероятность успешного использования артефакта: 67%',
		button: '',
	},
	{
		id: 'SPPescherni_Trolli',
		title: 'Пещерные Тролли',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Pescherni_Trolli.jpg'),
		image: require('../images/Storonie/SPPescherni_Trolli.jpg'),
		price: 210,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPRaion_Z',
		title: 'Район Зет',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Raion_Z.jpg'),
		image: require('../images/Storonie/SPRaion_Z.jpg'),
		price: 155,
		inBasket: false,
		directory: 'Вероятность успешного использования артефакта: 33.3%',
		button: '',
	},
	{
		id: 'SPRatmeni',
		title: 'Ратмены',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Ratmeni.jpg'),
		image: require('../images/Storonie/SPRatmeni.jpg'),
		price: 190,
		inBasket: false,
		directory:
			'Вероятность успешного использования артефакта: 67% (Орудие хотя бы повреждено)',
		button: '',
	},
	{
		id: 'SPRoga_i_Kopita',
		title: 'Рога И Копыта',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Roga_i_Kopita.jpg'),
		image: require('../images/Storonie/SPRoga_i_Kopita.jpg'),
		price: 185,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPSindikat',
		title: 'Синдикат',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Sindikat.jpg'),
		image: require('../images/Storonie/SPSindikat.jpg'),
		price: 200,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPStrazhi_Heridaka',
		title: 'Стражи Хердика',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Strazhi_Heridaka.jpg'),
		image: require('../images/Storonie/SPStrazhi_Heridaka.jpg'),
		price: 180,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPGarem_Sukkuba',
		title: 'Гарем Суккуба',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Garem_Sukkuba.jpg'),
		image: require('../images/Storonie/SPGarem_Sukkuba.jpg'),
		price: 190,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPHalflingy',
		title: 'Халфлинги',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Halflingy.jpg'),
		image: require('../images/Storonie/SPHalflingy.jpg'),
		price: 150,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPShpicbergen',
		title: 'Шпицберген',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Shpicbergen.jpg'),
		image: require('../images/Storonie/SPShpicbergen.jpg'),
		price: 195,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPEllada',
		title: 'Эллада',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/SPEllada.jpg'),
		image: require('../images/Storonie/SPEllada.jpg'),
		price: 190,
		inBasket: false,
		button: '',
	},
	{
		id: 'SPBagrovie_Balahony',
		title: 'Багровые Балахоны',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Bagrovie_Balahony.jpg'),
		image: require('../images/Storonie/SPBagrovie_Balahony.jpg'),
		price: 155,
		inBasket: false,
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPElfiski_Vedmy',
		title: 'Эльфийские Ведьмы',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Elfiski_Vedmy.jpg'),
		image: require('../images/Storonie/SPElfiski_Vedmy.jpg'),
		price: 190,
		inBasket: false,
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
	{
		id: 'SPAkkad',
		title: 'Аккад',
		category: 'Альянс Свободных (АОБФ)',
		description: require('../images/Artefakti/Akkad.jpg'),
		image: require('../images/Storonie/SPAkkad.jpg'),
		price: 185,
		inBasket: false,
		button: '',
		marker: require('../images/marker_new.png'),
		markerTitle: 'Новый адаптированный отряд',
	},
];
